<?php

return [
    ['method' => 'GET', 'path' => '/api/admin/loyalty/dashboard', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@dashboard', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/customers', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@customers', 'capability' => 'loyalty.admin'],
    ['method' => 'POST', 'path' => '/api/admin/loyalty/customers', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@createMember', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/customers/{memberId}', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@customerDetail', 'capability' => 'loyalty.admin'],
    ['method' => 'PATCH', 'path' => '/api/admin/loyalty/customers/{memberId}', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@updateMember', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/rewards', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@rewards', 'capability' => 'loyalty.admin'],
    ['method' => 'POST', 'path' => '/api/admin/loyalty/rewards', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@createReward', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/rewards/{rewardId}', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@rewardDetail', 'capability' => 'loyalty.admin'],
    ['method' => 'PATCH', 'path' => '/api/admin/loyalty/rewards/{rewardId}', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@updateReward', 'capability' => 'loyalty.admin'],
    ['method' => 'DELETE', 'path' => '/api/admin/loyalty/rewards/{rewardId}', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@deleteReward', 'capability' => 'loyalty.admin'],
    ['method' => 'POST', 'path' => '/api/admin/loyalty/redemptions', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@redeemReward', 'capability' => 'loyalty.admin'],
    ['method' => 'POST', 'path' => '/api/admin/loyalty/purchases', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@registerPurchase', 'capability' => 'loyalty.admin'],
    ['method' => 'POST', 'path' => '/api/admin/loyalty/purchases/{reference}/reverse', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@reversePurchase', 'capability' => 'loyalty.admin'],
    ['method' => 'POST', 'path' => '/api/admin/loyalty/adjustments', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@adjustPoints', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/settings', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@settings', 'capability' => 'loyalty.admin'],
    ['method' => 'PUT', 'path' => '/api/admin/loyalty/settings', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@updateSettings', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/rules', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@rules', 'capability' => 'loyalty.admin'],
    ['method' => 'PUT', 'path' => '/api/admin/loyalty/rules', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@updateRules', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/reports', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@reportsCatalog', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/reports/{reportKey}', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@report', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/reports/{reportKey}/export', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@exportReport', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/audit-events', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@auditEvents', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/risk-events', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@riskEvents', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/api-clients', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@apiClients', 'capability' => 'loyalty.admin'],
    ['method' => 'POST', 'path' => '/api/admin/loyalty/api-clients', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@createApiClient', 'capability' => 'loyalty.admin'],
    ['method' => 'PATCH', 'path' => '/api/admin/loyalty/api-clients/{clientId}', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@updateApiClient', 'capability' => 'loyalty.admin'],
    ['method' => 'POST', 'path' => '/api/admin/loyalty/api-clients/{clientId}/revoke', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@revokeApiClient', 'capability' => 'loyalty.admin'],
    ['method' => 'PATCH', 'path' => '/api/admin/loyalty/members/{memberId}/wallet', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@updateWallet', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/admin/loyalty/members/{memberId}/pass-preview', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@passPreview', 'capability' => 'loyalty.admin'],
    ['method' => 'POST', 'path' => '/api/admin/loyalty/wallet/google-link', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@googleWalletLink', 'capability' => 'loyalty.admin'],
    ['method' => 'GET', 'path' => '/api/loyalty/v1/health', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@externalHealth', 'capability' => 'loyalty.public'],
    ['method' => 'GET', 'path' => '/api/loyalty/v1/program', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@externalProgram', 'capability' => 'loyalty.public'],
    ['method' => 'GET', 'path' => '/api/loyalty/v1/members/{accountId}', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@externalMember', 'capability' => 'loyalty.public'],
    ['method' => 'POST', 'path' => '/api/loyalty/v1/members/upsert', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@externalMemberUpsert', 'capability' => 'loyalty.public'],
    ['method' => 'POST', 'path' => '/api/loyalty/v1/purchases', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@externalPurchase', 'capability' => 'loyalty.public'],
    ['method' => 'POST', 'path' => '/api/loyalty/v1/purchases/{reference}/reverse', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@externalPurchaseReverse', 'capability' => 'loyalty.public'],
    ['method' => 'POST', 'path' => '/api/loyalty/v1/redemptions', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@externalRedemption', 'capability' => 'loyalty.public'],
    ['method' => 'GET', 'path' => '/api/loyalty/v1/rewards', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@externalRewards', 'capability' => 'loyalty.public'],
    ['method' => 'GET', 'path' => '/api/loyalty/v1/reports/{reportKey}', 'handler' => 'App\\Modules\\LoyaltyRewards\\Controllers\\LoyaltyController@externalReport', 'capability' => 'loyalty.public'],
];
