<?php

return [
    ['method' => 'GET', 'path' => '/api/users', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\UserController@index', 'capability' => 'users.admin'],
    ['method' => 'POST', 'path' => '/api/users', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\UserController@store', 'capability' => 'users.admin'],
    ['method' => 'GET', 'path' => '/api/users/{id}', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\UserController@show', 'capability' => 'users.admin'],
    ['method' => 'PATCH', 'path' => '/api/users/{id}', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\UserController@patch', 'capability' => 'users.admin'],
    ['method' => 'PUT', 'path' => '/api/users/{id}', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\UserController@update', 'capability' => 'users.admin'],
    ['method' => 'POST', 'path' => '/api/users/{id}/unlock', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\UserController@unlock', 'capability' => 'users.admin'],
    ['method' => 'GET', 'path' => '/api/roles', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\RoleController@index', 'capability' => 'users.admin'],
    ['method' => 'POST', 'path' => '/api/roles', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\RoleController@store', 'capability' => 'users.admin'],
    ['method' => 'GET', 'path' => '/api/roles/{roleId}', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\RoleController@show', 'capability' => 'users.admin'],
    ['method' => 'PATCH', 'path' => '/api/roles/{roleId}', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\RoleController@update', 'capability' => 'users.admin'],
    ['method' => 'DELETE', 'path' => '/api/roles/{roleId}', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\RoleController@destroy', 'capability' => 'users.admin'],
    ['method' => 'GET', 'path' => '/api/user/addresses', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\UserController@getAddresses', 'capability' => 'users.profile'],
    ['method' => 'PUT', 'path' => '/api/user/addresses', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\UserController@updateAddresses', 'capability' => 'users.profile'],
    ['method' => 'GET', 'path' => '/api/user/profile', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\UserController@getProfile', 'capability' => 'users.profile'],
    ['method' => 'PUT', 'path' => '/api/user/profile', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\UserController@updateProfile', 'capability' => 'users.profile'],
    ['method' => 'PUT', 'path' => '/api/user/password', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\UserController@updatePassword', 'capability' => 'users.profile'],
    ['method' => 'POST', 'path' => '/api/auth/login', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\AuthController@login', 'capability' => 'users.auth'],
    ['method' => 'POST', 'path' => '/api/auth/logout', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\AuthController@logout', 'capability' => 'users.auth'],
    ['method' => 'POST', 'path' => '/api/auth/register', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\AuthController@register', 'capability' => 'users.auth'],
    ['method' => 'POST', 'path' => '/api/auth/request-otp', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\AuthController@requestOtp', 'capability' => 'users.auth'],
    ['method' => 'POST', 'path' => '/api/auth/verify-otp', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\AuthController@verifyOtp', 'capability' => 'users.auth'],
    ['method' => 'POST', 'path' => '/api/auth/password-reset/request', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\AuthController@requestPasswordReset', 'capability' => 'users.auth'],
    ['method' => 'POST', 'path' => '/api/auth/password-reset/confirm', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\AuthController@confirmPasswordReset', 'capability' => 'users.auth'],
    ['method' => 'GET', 'path' => '/api/auth/verify', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\AuthController@verify', 'capability' => 'users.auth'],
    ['method' => 'GET', 'path' => '/api/auth/session', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\AuthController@session', 'capability' => 'users.auth'],
    ['method' => 'GET', 'path' => '/api/tenant/context', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\TenantController@context', 'capability' => 'users.auth'],
    ['method' => 'GET', 'path' => '/api/admin/tenants', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\TenantController@adminIndex', 'capability' => 'admin.tenants'],
    ['method' => 'POST', 'path' => '/api/admin/tenants', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\TenantController@adminCreate', 'capability' => 'admin.tenants'],
    ['method' => 'PATCH', 'path' => '/api/admin/tenants/{tenantId}/modules', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\TenantController@adminUpdateModules', 'capability' => 'admin.tenants'],
    ['method' => 'PATCH', 'path' => '/api/admin/tenants/{tenantId}/configuration', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\TenantController@adminUpdateConfiguration', 'capability' => 'admin.tenants'],
    ['method' => 'GET', 'path' => '/api/admin/settings/session', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\SessionSettingsController@getSessionSettings', 'capability' => 'admin.settings'],
    ['method' => 'PUT', 'path' => '/api/admin/settings/session', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\SessionSettingsController@updateSessionSettings', 'capability' => 'admin.settings'],
    ['method' => 'GET', 'path' => '/api/health', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\HealthController@status', 'capability' => 'system.health'],
    ['method' => 'POST', 'path' => '/api/security/csp-report', 'handler' => 'App\\Modules\\IdentityPlatform\\Controllers\\SecurityTelemetryController@cspReport', 'capability' => 'security.telemetry'],
];
