<?php

return [
    ['method' => 'GET', 'path' => '/health', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@health', 'capability' => 'system.health'],
    ['method' => 'HEAD', 'path' => '/health', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@health', 'capability' => 'system.health'],
    ['method' => 'GET', 'path' => '/api/{apiMode}/v1/configuration', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@configuration', 'capability' => 'billing.documents'],
    ['method' => 'POST', 'path' => '/api/{apiMode}/v1/configuration', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@updateConfiguration', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'POST', 'path' => '/api/{apiMode}/v1/configuration/certificate', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@uploadCertificate', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'POST', 'path' => '/api/{apiMode}/v1/configuration/branches', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@createBranch', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'POST', 'path' => '/api/{apiMode}/v1/configuration/branches/{branchId}', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@updateBranch', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'POST', 'path' => '/api/{apiMode}/v1/invoices', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@emit', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'GET', 'path' => '/api/{apiMode}/v1/invoices/rides', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@rides', 'capability' => 'billing.documents'],
    ['method' => 'GET', 'path' => '/api/{apiMode}/v1/invoices/source/{sourceReference}', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@source', 'capability' => 'billing.documents'],
    ['method' => 'GET', 'path' => '/api/{apiMode}/v1/invoices/{accessKey}/status', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@status', 'capability' => 'billing.documents'],
    ['method' => 'GET', 'path' => '/api/{apiMode}/v1/invoices/{accessKey}/xml', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@xml', 'capability' => 'billing.documents'],
    ['method' => 'GET', 'path' => '/api/{apiMode}/v1/invoices/{accessKey}/ride.pdf', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@ridePdf', 'capability' => 'billing.documents'],
    ['method' => 'POST', 'path' => '/api/{apiMode}/v1/invoices/{accessKey}/mail-test', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@mailTest', 'capability' => 'mail.billing'],
    ['method' => 'POST', 'path' => '/api/{apiMode}/v1/invoices/{accessKey}/cancel-and-reissue', 'handler' => 'App\\Modules\\Billing\\Controllers\\PublicBillingController@cancelAndReissue', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'GET', 'path' => '/api/admin/billing/health', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@health', 'capability' => 'system.health'],
    ['method' => 'GET', 'path' => '/api/admin/billing/configuration', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@configuration', 'capability' => 'billing.documents'],
    ['method' => 'PATCH', 'path' => '/api/admin/billing/configuration', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@updateConfiguration', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'POST', 'path' => '/api/admin/billing/configuration/certificate', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@uploadCertificate', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'POST', 'path' => '/api/admin/billing/configuration/branches', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@createBranch', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'PATCH', 'path' => '/api/admin/billing/configuration/branches/{branchId}', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@updateBranch', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'GET', 'path' => '/api/admin/billing/products', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@products', 'capability' => 'billing.documents'],
    ['method' => 'POST', 'path' => '/api/admin/billing/products', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@storeProduct', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'POST', 'path' => '/api/admin/billing/invoices', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@emit', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'POST', 'path' => '/api/admin/billing/invoices/from-products', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@emitFromProducts', 'capability' => 'billing.sri.pruebas'],
    ['method' => 'GET', 'path' => '/api/admin/billing/invoices/source/{sourceReference}', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@source', 'capability' => 'billing.documents'],
    ['method' => 'GET', 'path' => '/api/admin/billing/invoices/{accessKey}/status', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@status', 'capability' => 'billing.documents'],
    ['method' => 'GET', 'path' => '/api/admin/billing/invoices/{accessKey}/xml', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@xml', 'capability' => 'billing.documents'],
    ['method' => 'GET', 'path' => '/api/admin/billing/rides', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@rides', 'capability' => 'billing.documents'],
    ['method' => 'GET', 'path' => '/api/admin/billing/rides/{accessKey}/pdf', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@ridePdf', 'capability' => 'billing.documents'],
    ['method' => 'POST', 'path' => '/api/admin/billing/rides/{accessKey}/mail-test', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@mailTest', 'capability' => 'mail.billing'],
    ['method' => 'POST', 'path' => '/api/admin/billing/rides/{accessKey}/cancel-and-reissue', 'handler' => 'App\\Modules\\Billing\\Controllers\\BillingDocumentController@cancelAndReissue', 'capability' => 'billing.documents'],
];
